# Generated by asn1c. Use 'make' to compile the converter example.
#
# If compiling manually without make, you must:
# 1. Use the -S flag when running asn1c to copy all required skeleton files
# 2. Compile with: -I. -lm flags
# 3. Include ALL .c files in the directory
#
# Recommended: just use 'make' instead of manual compilation

include Makefile.am.libasncodec

LIBS += -lm
CFLAGS += $(ASN_MODULE_CFLAGS) -DASN_PDU_COLLECTION -I.
ASN_LIBRARY ?= libasncodec.a
ASN_PROGRAM ?= converter-example
ASN_PROGRAM_SRCS ?= \
	converter-example.c\
	pdu_collection.c

all: $(ASN_PROGRAM)

$(ASN_PROGRAM): $(ASN_LIBRARY) $(ASN_PROGRAM_SRCS:.c=.o)
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $(ASN_PROGRAM) $(ASN_PROGRAM_SRCS:.c=.o) $(LDFLAGS) $(ASN_LIBRARY) $(LIBS)

$(ASN_LIBRARY): $(ASN_MODULE_SRCS:.c=.o)
	$(AR) rcs $@ $(ASN_MODULE_SRCS:.c=.o)

# Track header dependencies so that objects are rebuilt when any
# included header (e.g. a skeleton header) changes. Without this,
# stale objects compiled against an older header layout may be
# linked together, causing hard-to-debug memory corruption.
DEPFLAGS = -MMD -MP

%.o: %.c
	$(CC) $(CFLAGS) $(DEPFLAGS) -o $@ -c $<

-include $(ASN_MODULE_SRCS:.c=.d) $(ASN_PROGRAM_SRCS:.c=.d)

clean:
	rm -f $(ASN_PROGRAM) $(ASN_LIBRARY)
	rm -f $(ASN_MODULE_SRCS:.c=.o) $(ASN_PROGRAM_SRCS:.c=.o)
	rm -f $(ASN_MODULE_SRCS:.c=.d) $(ASN_PROGRAM_SRCS:.c=.d)

regen: regenerate-from-asn1-source

regenerate-from-asn1-source:
	/home/runner/work/asn1c/asn1c/asn1c/asn1c -S /home/runner/work/asn1c/asn1c/skeletons -flink-skeletons -Wdebug-compiler /home/runner/work/asn1c/asn1c/tests/tests-asn1c-compiler/70-xer-test-OK.asn1

