#!/bin/sh

# Test that version string differences in generated output don't cause test failures.
# The check-parsing.sh test harness strips version strings (via sed) from both
# the golden reference file and the newly-generated compiler output before
# comparing them.  This script verifies that stripping logic is correct and
# that only version-string-only differences are ignored while real content
# differences are still caught.

# Test diff(1) capabilities (mirror check-parsing.sh)
diff -a . . 2>/dev/null && diffArgs="-a"
diff -u . . 2>/dev/null && diffArgs="$diffArgs -u"

PASSED=0
FAILED=0

# Helper: apply the same sed transformations used in check-parsing.sh
strip_version() {
    LC_ALL=C sed \
        -e 's/^found in .*/found in .../' \
        -e 's/asn1c-[^ ]* ([^)]*)/asn1c/g' \
        -e 's/asn1c-[^ >]*/asn1c/g'
}

TMPDIR_TEST=$(mktemp -d)
trap 'rm -rf "$TMPDIR_TEST"' EXIT

# ---------------------------------------------------------------------------
# Test 1: Files that differ ONLY in version string must compare as equal
# ---------------------------------------------------------------------------

cat > "$TMPDIR_TEST/ref.txt" << 'ENDOFFILE'
/*** <<< INCLUDES [T] >>> ***/

/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Test"
 */
typedef int T_t;
ENDOFFILE

cat > "$TMPDIR_TEST/new.txt" << 'ENDOFFILE'
/*** <<< INCLUDES [T] >>> ***/

/*
 * Generated by asn1c-c557ce3-dirty-2026-05-01 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "Test"
 */
typedef int T_t;
ENDOFFILE

strip_version < "$TMPDIR_TEST/ref.txt" > "$TMPDIR_TEST/ref_stripped.txt"
strip_version < "$TMPDIR_TEST/new.txt" > "$TMPDIR_TEST/new_stripped.txt"

if diff $diffArgs "$TMPDIR_TEST/ref_stripped.txt" "$TMPDIR_TEST/new_stripped.txt" > /dev/null 2>&1; then
    echo "PASS: version-only difference is correctly ignored"
    PASSED=$((PASSED + 1))
else
    echo "FAIL: version-only difference should have been ignored"
    FAILED=$((FAILED + 1))
fi

# ---------------------------------------------------------------------------
# Test 2: Files that differ ONLY in version string (no URL) compare as equal
# ---------------------------------------------------------------------------

cat > "$TMPDIR_TEST/ref2.txt" << 'ENDOFFILE'
/* Generated by asn1c-0.9.29 */
typedef int T_t;
ENDOFFILE

cat > "$TMPDIR_TEST/new2.txt" << 'ENDOFFILE'
/* Generated by asn1c-051ba13-2026-05-03 */
typedef int T_t;
ENDOFFILE

strip_version < "$TMPDIR_TEST/ref2.txt" > "$TMPDIR_TEST/ref2_stripped.txt"
strip_version < "$TMPDIR_TEST/new2.txt" > "$TMPDIR_TEST/new2_stripped.txt"

if diff $diffArgs "$TMPDIR_TEST/ref2_stripped.txt" "$TMPDIR_TEST/new2_stripped.txt" > /dev/null 2>&1; then
    echo "PASS: version-only difference (no URL) is correctly ignored"
    PASSED=$((PASSED + 1))
else
    echo "FAIL: version-only difference (no URL) should have been ignored"
    FAILED=$((FAILED + 1))
fi

# ---------------------------------------------------------------------------
# Test 3: Files with identical version strings also compare as equal
# ---------------------------------------------------------------------------

cat > "$TMPDIR_TEST/ref3.txt" << 'ENDOFFILE'
/* Generated by asn1c-0.9.29 (http://lionet.info/asn1c) */
typedef int T_t;
ENDOFFILE

cp "$TMPDIR_TEST/ref3.txt" "$TMPDIR_TEST/new3.txt"

strip_version < "$TMPDIR_TEST/ref3.txt" > "$TMPDIR_TEST/ref3_stripped.txt"
strip_version < "$TMPDIR_TEST/new3.txt" > "$TMPDIR_TEST/new3_stripped.txt"

if diff $diffArgs "$TMPDIR_TEST/ref3_stripped.txt" "$TMPDIR_TEST/new3_stripped.txt" > /dev/null 2>&1; then
    echo "PASS: identical files compare as equal"
    PASSED=$((PASSED + 1))
else
    echo "FAIL: identical files should compare as equal"
    FAILED=$((FAILED + 1))
fi

# ---------------------------------------------------------------------------
# Test 4: Files with non-version content differences must still fail
# ---------------------------------------------------------------------------

cat > "$TMPDIR_TEST/ref4.txt" << 'ENDOFFILE'
/* Generated by asn1c-0.9.29 (http://lionet.info/asn1c) */
typedef int T_t;
ENDOFFILE

cat > "$TMPDIR_TEST/new4.txt" << 'ENDOFFILE'
/* Generated by asn1c-c557ce3 (https://github.com/mouse07410/asn1c) */
typedef long T_t;
ENDOFFILE

strip_version < "$TMPDIR_TEST/ref4.txt" > "$TMPDIR_TEST/ref4_stripped.txt"
strip_version < "$TMPDIR_TEST/new4.txt" > "$TMPDIR_TEST/new4_stripped.txt"

if diff $diffArgs "$TMPDIR_TEST/ref4_stripped.txt" "$TMPDIR_TEST/new4_stripped.txt" > /dev/null 2>&1; then
    echo "FAIL: real content differences should still be detected"
    FAILED=$((FAILED + 1))
else
    echo "PASS: real content differences are still correctly detected"
    PASSED=$((PASSED + 1))
fi

# ---------------------------------------------------------------------------
# Test 5: Integration — compile an ASN.1 module, compare against a golden
#          reference that carries a different version string.
# ---------------------------------------------------------------------------

top_srcdir="${top_srcdir:-../..}"
top_builddir="${top_builddir:-../..}"

ASN1C="${top_builddir}/asn1c/asn1c"
SKELETONS="${top_srcdir}/skeletons"

# Only run integration test when the compiler binary is available
if [ -x "$ASN1C" ]; then
    # Pick a simple known-good input module (no-fail guaranteed)
    asn_src="${top_srcdir}/tests/tests-asn1c-compiler/03-enum-OK.asn1"

    # Generate fresh output
    "$ASN1C" -S "$SKELETONS" -no-gen-OER -no-gen-UPER -no-gen-APER -no-gen-JER \
        -E -F "$asn_src" 2>/dev/null \
        | strip_version > "$TMPDIR_TEST/live_stripped.txt"

    # Build a "golden reference" with a deliberately different version string
    "$ASN1C" -S "$SKELETONS" -no-gen-OER -no-gen-UPER -no-gen-APER -no-gen-JER \
        -E -F "$asn_src" 2>/dev/null \
        | LC_ALL=C sed \
            -e 's/asn1c-[^ ]* ([^)]*)/asn1c-FAKE-VERSION (https:\/\/example.com)/g' \
            -e 's/asn1c-[^ >]*/asn1c-FAKE-VERSION/g' \
        | strip_version > "$TMPDIR_TEST/golden_stripped.txt"

    if diff $diffArgs "$TMPDIR_TEST/golden_stripped.txt" "$TMPDIR_TEST/live_stripped.txt" > /dev/null 2>&1; then
        echo "PASS: integration — compiler output matches reference after version stripping"
        PASSED=$((PASSED + 1))
    else
        echo "FAIL: integration — compiler output should match reference after version stripping"
        diff $diffArgs "$TMPDIR_TEST/golden_stripped.txt" "$TMPDIR_TEST/live_stripped.txt" >&2
        FAILED=$((FAILED + 1))
    fi
else
    echo "SKIP: asn1c binary not found at $ASN1C — skipping integration test"
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

echo ""
echo "Results: $PASSED passed, $FAILED failed"

if [ "$FAILED" -ne 0 ]; then
    exit 1
fi

exit 0
